const hogs = [
  {
    id: 1,
    name: 'Mudblood',
    specialty: 'Mediocre magic',
    greased: false,
    weightRatio: 2.0,
    medal: 'bronze',
  },
  {
    id: 2,
    name: 'Porkchop',
    specialty: 'Making friends',
    greased: true,
    weightRatio: 1.6,
    medal: 'silver',
  },
  {
    id: 3,
    name: 'Cherub',
    specialty: 'truffle finder',
    greased: false,
    weightRatio: 0.7,
    medal: 'gold',
  },
  {
    id: 4,
    name: 'Piggy smalls',
    specialty: 'Massivity',
    greased: true,
    weightRatio: 5.1,
    medal: 'platinum',
  },
  {
    id: 5,
    name: 'Trouble',
    specialty: 'Racing',
    greased: true,
    weightRatio: 1.7,
    medal: 'gold',
  },
  {
    id: 6,
    name: 'Sobriety',
    specialty: 'Expert Witness',
    greased: false,
    weightRatio: 2.2,
    medal: 'silver',
  },
  {
    id: 7,
    name: 'Rainbowdash',
    specialty: 'Union Busting',
    greased: false,
    weightRatio: 3.7,
    medal: 'wood',
  },
  {
    id: 8,
    name: 'TruffleShuffle',
    specialty: 'Finding truffles',
    greased: true,
    weightRatio: 4.0,
    medal: 'gold',
  },
  {
    id: 9,
    name: 'Bay of Pigs',
    specialty: 'Hamphlet Distribution',
    greased: false,
    weightRatio: 2.8,
    medal: 'diamond',
  },
  {
    id: 10,
    name: 'The Prosciutto Concern',
    specialty: 'truffle finder',
    greased: false,
    weightRatio: 2.3,
    medal: 'bronze',
  },
  {
    id: 11,
    name: 'Galaxy Note',
    specialty: 'Airport Security',
    greased: true,
    weightRatio: 1.9,
    medal: 'diamond',
  },
  {
    id: 12,
    name: 'Leggo My Eggo',
    specialty: 'Babysitting',
    greased: true,
    weightRatio: 3.3,
    medal: 'platinum',
  },
  {
    id: 13,
    name: 'Augustus Gloop',
    specialty: 'Vacuum tubes',
    greased: true,
    weightRatio: 4.1,
    medal: 'wood',
  }
];

export default hogs;
